### ISSUE TITLE
这个是因为显存不够还是什么？

### ISSUE THREAD

**Issue by af-74413592** [OpenLMLab/MOSS#67]
│ /home/ubuntu/.cache/huggingface/modules/transformers_modules/fnlp/moss-moon- │
│ 003-sft/dc39155402a323c3ad85ac9c4cb02556c61594f1/modeling_moss.py:53 in      │
│ apply_rotary_pos_emb                                                         │
│                                                                              │
│    50                                                                        │
│    51 # Copied from transformers.models.gptj.modeling_gptj.apply_rotary_pos_ │
│    52 def apply_rotary_pos_emb(tensor: torch.Tensor, sin: torch.Tensor, cos: │
│ ❱  53 │   sin = torch.repeat_interleave(sin[:, :, None, :], 2, 3)            │
│    54 │   cos = torch.repeat_interleave(cos[:, :, None, :], 2, 3)            │
│    55 │   return (tensor * cos) + (rotate_every_two(tensor) * sin)           │
│    56                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so 
the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by WanJuWuGo** [comment]
版本不对。安装新版本就行
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

**Comment by piglaker** [comment]
请问您解决了吗，

**Comment by wktdwktd** [comment]
> 请问您解决了吗，

我按照这个 解决了
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

![img_v2_5155b4df-cc15-4a4d-a03d-9eb6a6e5510g](https://user-images.githubusercontent.com/127709336/233840246-8b3b3e5f-032a-45df-b4ab-a9b9d358852a.jpg)
![s0TApeHjWb](https://user-images.githubusercontent.com/127709336/233840257-f7dd9e5d-3b2b-456a-b4bf-e5536c33e300.jpg)

**Comment by baigang666** [comment]
> > 请问您解决了吗，
> 
> 我按照这个 解决了 pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
> 
> ![img_v2_5155b4df-cc15-4a4d-a03d-9eb6a6e5510g](https://user-images.githubusercontent.com/127709336/233840246-8b3b3e5f-032a-45df-b4ab-a9b9d358852a.jpg) ![s0TApeHjWb](https://user-images.githubusercontent.com/127709336/233840257-f7dd9e5d-3b2b-456a-b4bf-e5536c33e300.jpg)

请问我就是图中这个版本，在A100上尝试，几次问答后，依然报同样的错误。请问怎么解决
